
version: '3'
services:
  graph-node:
    build: .
    ports:
      - 8000:8000
      - 8001:8001
      - 8020:8020
    depends_on:
      - ipfs
      - postgres
    environment:
      postgres_host: postgres:5432
      postgres_user: postgres
      postgres_pass: ${POSTGRES_PASSWORD}
      postgres_db: postgres
      ipfs: ipfs:5001
      ethereum: ${ETHEREUM}
  ipfs:
    image: ipfs/go-ipfs
    ports:
      - 5001:5001
    volumes:
      - ./data/ipfs:/data/ipfs
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
